version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: chat-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: chat_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - chat-network

  postgres:
    image: postgres:latest
    container_name: chat-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

  redis:
    image: redis:alpine
    container_name: chat-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mongodb_data:
  postgres_data:
  redis_data:
